---
title: "Sales Forecasting - Initial Results"
author: "Eunchong Jung"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("readxl")
#install.packages("corrgram")
#install.packages("car")
#install.packages("lubridate")
#install.packages("plyr")

library(readxl)
library(corrgram)
library(car)
library(lubridate)
library(plyr)
```


```{r pressure, echo=FALSE}
#plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


Exploratory Data Analysis

Stores Data
```{r}
stores_raw <- read.csv("stores.csv")
stores_raw$Store <- as.factor(stores_raw$Store)
str(stores_raw)
summary(stores_raw)

# outliers
Boxplot(Size~Type, data = stores_raw, id.method = "y")
stores_raw[c(33, 36, 3, 5),]
stores_clean <- stores_raw
aggregate(stores_clean$Size, list(stores_clean$Type), mean)

# replace outliers to Type "C" since values are similar to the mean of "C" stores
stores_clean[c(33, 36, 3, 5),2] <- "C"


# check NAs
sum(is.na(stores_clean))

summary(stores_clean)


```

Training Data
```{r}
train_raw <- read.csv("train.csv")
str(train_raw)
summary(train_raw)
train_clean <- train_raw
train_clean$Store <- as.factor(train_clean$Store)
train_clean$Dept <- as.factor(train_clean$Dept)

# check missing depts in each store
stores_unique <- levels(train_clean$Store)
depts_unique <- levels(train_clean$Dept)
stores_list <- as.list(stores_unique)
check_depts <- function(x) {
  identical(levels(train_clean[train_clean$Store == x, 2]), depts_unique)
}
summary(sapply(stores_list, check_depts))

# check missing dates
train_clean$Date <- as.Date(train_clean$Date)
dates_unique <- unique(train_clean$Date)
dates_generated <- seq(min(train_clean$Date), max(train_clean$Date), by = "week")
identical(dates_unique, dates_generated)

# outliers; not removed due to vast difference of sales between stores
Boxplot(train_clean$Weekly_Sales)

# check NAs
sum(is.na(train_clean))

# convert dates to day of week & week number
# unused (all values are Friday): train_clean$day_of_week <- wday(train_clean$Date, label = TRUE)
train_clean$week_number <- as.factor(week(train_clean$Date))

summary(train_clean)
str(train_clean)
```

Features Data
```{r}
features_raw <- read.csv("features.csv")
str(features_raw)
features_clean <- features_raw
features_clean$Store <- as.factor(features_clean$Store)
features_clean$Date  <- as.Date(features_clean$Date)


# check NAs; CPI, Unemployment, IsHoliday have 585 NAs corresponding to 13 extra weeks * 45 stores = 585, not found in training data; disregard
sum(is.na(features_clean))

# remove MarkDowns; too many NAs
# explore MarkDowns later
features_clean <- features_clean[, c(1:4, 10:12)]
str(features_clean)
summary(features_clean)
```

Combine datasets
```{r}
df <- join(train_clean, stores_clean, by = "Store", type = "left")
df <- join(df, features_clean, by = c("Store", "Date"), type = "left")
df <- df[-3]
identical(df$IsHoliday, df$IsHoliday.1)
df$IsHoliday.1 <- NULL
```


Multiple Regression
```{r}
# Split the dataset to 80% training and 20% test sets
rn_train <- sample(nrow(df), floor(nrow(df)*0.8))
train <- df[rn_train,]
test <- df[-rn_train,]

model <- lm(Weekly_Sales ~ ., data = train)
summary(model)
# CPI & Size not statistically significant; remove
train$CPI <- NULL
train$Size <- NULL

model <- lm(Weekly_Sales ~ ., data = train)
summary(model)

prediction <- predict(model, interval = "prediction", newdata = test)


# Errors
errors <- prediction[, "fit"] - test$Weekly_Sales
hist(errors)

# Root Mean Squared Error & Percentage of cases with less than 25% error 
rmse <- sqrt(sum((prediction[,"fit"] - test$Weekly_Sales)^2)/nrow(test))
rel_change <- 1 - ((test$Weekly_Sales - abs(errors)) / test$Weekly_Sales)
pred25 <- table(rel_change<0.25)["TRUE"] / nrow(test)
paste("RMSE:", rmse)
paste("PRED(25):", pred25)
```

